	soc_system u0 (
		.clk_clk                                     (<connected-to-clk_clk>),                                     //                            clk.clk
		.clock_bridge_0_out_clk_clk                  (<connected-to-clock_bridge_0_out_clk_clk>),                  //         clock_bridge_0_out_clk.clk
		.clock_bridge_44_out_clk_clk                 (<connected-to-clock_bridge_44_out_clk_clk>),                 //        clock_bridge_44_out_clk.clk
		.clock_bridge_48_out_clk_clk                 (<connected-to-clock_bridge_48_out_clk_clk>),                 //        clock_bridge_48_out_clk.clk
		.hps_0_f2h_dma_req0_dma_req                  (<connected-to-hps_0_f2h_dma_req0_dma_req>),                  //             hps_0_f2h_dma_req0.dma_req
		.hps_0_f2h_dma_req0_dma_single               (<connected-to-hps_0_f2h_dma_req0_dma_single>),               //                               .dma_single
		.hps_0_f2h_dma_req0_dma_ack                  (<connected-to-hps_0_f2h_dma_req0_dma_ack>),                  //                               .dma_ack
		.hps_0_f2h_dma_req1_dma_req                  (<connected-to-hps_0_f2h_dma_req1_dma_req>),                  //             hps_0_f2h_dma_req1.dma_req
		.hps_0_f2h_dma_req1_dma_single               (<connected-to-hps_0_f2h_dma_req1_dma_single>),               //                               .dma_single
		.hps_0_f2h_dma_req1_dma_ack                  (<connected-to-hps_0_f2h_dma_req1_dma_ack>),                  //                               .dma_ack
		.hps_0_f2h_dma_req2_dma_req                  (<connected-to-hps_0_f2h_dma_req2_dma_req>),                  //             hps_0_f2h_dma_req2.dma_req
		.hps_0_f2h_dma_req2_dma_single               (<connected-to-hps_0_f2h_dma_req2_dma_single>),               //                               .dma_single
		.hps_0_f2h_dma_req2_dma_ack                  (<connected-to-hps_0_f2h_dma_req2_dma_ack>),                  //                               .dma_ack
		.hps_0_f2h_dma_req3_dma_req                  (<connected-to-hps_0_f2h_dma_req3_dma_req>),                  //             hps_0_f2h_dma_req3.dma_req
		.hps_0_f2h_dma_req3_dma_single               (<connected-to-hps_0_f2h_dma_req3_dma_single>),               //                               .dma_single
		.hps_0_f2h_dma_req3_dma_ack                  (<connected-to-hps_0_f2h_dma_req3_dma_ack>),                  //                               .dma_ack
		.hps_0_h2f_reset_reset_n                     (<connected-to-hps_0_h2f_reset_reset_n>),                     //                hps_0_h2f_reset.reset_n
		.hps_io_hps_io_emac1_inst_TX_CLK             (<connected-to-hps_io_hps_io_emac1_inst_TX_CLK>),             //                         hps_io.hps_io_emac1_inst_TX_CLK
		.hps_io_hps_io_emac1_inst_TXD0               (<connected-to-hps_io_hps_io_emac1_inst_TXD0>),               //                               .hps_io_emac1_inst_TXD0
		.hps_io_hps_io_emac1_inst_TXD1               (<connected-to-hps_io_hps_io_emac1_inst_TXD1>),               //                               .hps_io_emac1_inst_TXD1
		.hps_io_hps_io_emac1_inst_TXD2               (<connected-to-hps_io_hps_io_emac1_inst_TXD2>),               //                               .hps_io_emac1_inst_TXD2
		.hps_io_hps_io_emac1_inst_TXD3               (<connected-to-hps_io_hps_io_emac1_inst_TXD3>),               //                               .hps_io_emac1_inst_TXD3
		.hps_io_hps_io_emac1_inst_RXD0               (<connected-to-hps_io_hps_io_emac1_inst_RXD0>),               //                               .hps_io_emac1_inst_RXD0
		.hps_io_hps_io_emac1_inst_MDIO               (<connected-to-hps_io_hps_io_emac1_inst_MDIO>),               //                               .hps_io_emac1_inst_MDIO
		.hps_io_hps_io_emac1_inst_MDC                (<connected-to-hps_io_hps_io_emac1_inst_MDC>),                //                               .hps_io_emac1_inst_MDC
		.hps_io_hps_io_emac1_inst_RX_CTL             (<connected-to-hps_io_hps_io_emac1_inst_RX_CTL>),             //                               .hps_io_emac1_inst_RX_CTL
		.hps_io_hps_io_emac1_inst_TX_CTL             (<connected-to-hps_io_hps_io_emac1_inst_TX_CTL>),             //                               .hps_io_emac1_inst_TX_CTL
		.hps_io_hps_io_emac1_inst_RX_CLK             (<connected-to-hps_io_hps_io_emac1_inst_RX_CLK>),             //                               .hps_io_emac1_inst_RX_CLK
		.hps_io_hps_io_emac1_inst_RXD1               (<connected-to-hps_io_hps_io_emac1_inst_RXD1>),               //                               .hps_io_emac1_inst_RXD1
		.hps_io_hps_io_emac1_inst_RXD2               (<connected-to-hps_io_hps_io_emac1_inst_RXD2>),               //                               .hps_io_emac1_inst_RXD2
		.hps_io_hps_io_emac1_inst_RXD3               (<connected-to-hps_io_hps_io_emac1_inst_RXD3>),               //                               .hps_io_emac1_inst_RXD3
		.hps_io_hps_io_qspi_inst_IO0                 (<connected-to-hps_io_hps_io_qspi_inst_IO0>),                 //                               .hps_io_qspi_inst_IO0
		.hps_io_hps_io_qspi_inst_IO1                 (<connected-to-hps_io_hps_io_qspi_inst_IO1>),                 //                               .hps_io_qspi_inst_IO1
		.hps_io_hps_io_qspi_inst_IO2                 (<connected-to-hps_io_hps_io_qspi_inst_IO2>),                 //                               .hps_io_qspi_inst_IO2
		.hps_io_hps_io_qspi_inst_IO3                 (<connected-to-hps_io_hps_io_qspi_inst_IO3>),                 //                               .hps_io_qspi_inst_IO3
		.hps_io_hps_io_qspi_inst_SS0                 (<connected-to-hps_io_hps_io_qspi_inst_SS0>),                 //                               .hps_io_qspi_inst_SS0
		.hps_io_hps_io_qspi_inst_CLK                 (<connected-to-hps_io_hps_io_qspi_inst_CLK>),                 //                               .hps_io_qspi_inst_CLK
		.hps_io_hps_io_sdio_inst_CMD                 (<connected-to-hps_io_hps_io_sdio_inst_CMD>),                 //                               .hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0                  (<connected-to-hps_io_hps_io_sdio_inst_D0>),                  //                               .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1                  (<connected-to-hps_io_hps_io_sdio_inst_D1>),                  //                               .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK                 (<connected-to-hps_io_hps_io_sdio_inst_CLK>),                 //                               .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2                  (<connected-to-hps_io_hps_io_sdio_inst_D2>),                  //                               .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3                  (<connected-to-hps_io_hps_io_sdio_inst_D3>),                  //                               .hps_io_sdio_inst_D3
		.hps_io_hps_io_usb1_inst_D0                  (<connected-to-hps_io_hps_io_usb1_inst_D0>),                  //                               .hps_io_usb1_inst_D0
		.hps_io_hps_io_usb1_inst_D1                  (<connected-to-hps_io_hps_io_usb1_inst_D1>),                  //                               .hps_io_usb1_inst_D1
		.hps_io_hps_io_usb1_inst_D2                  (<connected-to-hps_io_hps_io_usb1_inst_D2>),                  //                               .hps_io_usb1_inst_D2
		.hps_io_hps_io_usb1_inst_D3                  (<connected-to-hps_io_hps_io_usb1_inst_D3>),                  //                               .hps_io_usb1_inst_D3
		.hps_io_hps_io_usb1_inst_D4                  (<connected-to-hps_io_hps_io_usb1_inst_D4>),                  //                               .hps_io_usb1_inst_D4
		.hps_io_hps_io_usb1_inst_D5                  (<connected-to-hps_io_hps_io_usb1_inst_D5>),                  //                               .hps_io_usb1_inst_D5
		.hps_io_hps_io_usb1_inst_D6                  (<connected-to-hps_io_hps_io_usb1_inst_D6>),                  //                               .hps_io_usb1_inst_D6
		.hps_io_hps_io_usb1_inst_D7                  (<connected-to-hps_io_hps_io_usb1_inst_D7>),                  //                               .hps_io_usb1_inst_D7
		.hps_io_hps_io_usb1_inst_CLK                 (<connected-to-hps_io_hps_io_usb1_inst_CLK>),                 //                               .hps_io_usb1_inst_CLK
		.hps_io_hps_io_usb1_inst_STP                 (<connected-to-hps_io_hps_io_usb1_inst_STP>),                 //                               .hps_io_usb1_inst_STP
		.hps_io_hps_io_usb1_inst_DIR                 (<connected-to-hps_io_hps_io_usb1_inst_DIR>),                 //                               .hps_io_usb1_inst_DIR
		.hps_io_hps_io_usb1_inst_NXT                 (<connected-to-hps_io_hps_io_usb1_inst_NXT>),                 //                               .hps_io_usb1_inst_NXT
		.hps_io_hps_io_spim1_inst_CLK                (<connected-to-hps_io_hps_io_spim1_inst_CLK>),                //                               .hps_io_spim1_inst_CLK
		.hps_io_hps_io_spim1_inst_MOSI               (<connected-to-hps_io_hps_io_spim1_inst_MOSI>),               //                               .hps_io_spim1_inst_MOSI
		.hps_io_hps_io_spim1_inst_MISO               (<connected-to-hps_io_hps_io_spim1_inst_MISO>),               //                               .hps_io_spim1_inst_MISO
		.hps_io_hps_io_spim1_inst_SS0                (<connected-to-hps_io_hps_io_spim1_inst_SS0>),                //                               .hps_io_spim1_inst_SS0
		.hps_io_hps_io_uart0_inst_RX                 (<connected-to-hps_io_hps_io_uart0_inst_RX>),                 //                               .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX                 (<connected-to-hps_io_hps_io_uart0_inst_TX>),                 //                               .hps_io_uart0_inst_TX
		.hps_io_hps_io_i2c0_inst_SDA                 (<connected-to-hps_io_hps_io_i2c0_inst_SDA>),                 //                               .hps_io_i2c0_inst_SDA
		.hps_io_hps_io_i2c0_inst_SCL                 (<connected-to-hps_io_hps_io_i2c0_inst_SCL>),                 //                               .hps_io_i2c0_inst_SCL
		.hps_io_hps_io_i2c1_inst_SDA                 (<connected-to-hps_io_hps_io_i2c1_inst_SDA>),                 //                               .hps_io_i2c1_inst_SDA
		.hps_io_hps_io_i2c1_inst_SCL                 (<connected-to-hps_io_hps_io_i2c1_inst_SCL>),                 //                               .hps_io_i2c1_inst_SCL
		.hps_io_hps_io_gpio_inst_GPIO09              (<connected-to-hps_io_hps_io_gpio_inst_GPIO09>),              //                               .hps_io_gpio_inst_GPIO09
		.hps_io_hps_io_gpio_inst_GPIO35              (<connected-to-hps_io_hps_io_gpio_inst_GPIO35>),              //                               .hps_io_gpio_inst_GPIO35
		.hps_io_hps_io_gpio_inst_GPIO40              (<connected-to-hps_io_hps_io_gpio_inst_GPIO40>),              //                               .hps_io_gpio_inst_GPIO40
		.hps_io_hps_io_gpio_inst_GPIO48              (<connected-to-hps_io_hps_io_gpio_inst_GPIO48>),              //                               .hps_io_gpio_inst_GPIO48
		.hps_io_hps_io_gpio_inst_GPIO53              (<connected-to-hps_io_hps_io_gpio_inst_GPIO53>),              //                               .hps_io_gpio_inst_GPIO53
		.hps_io_hps_io_gpio_inst_GPIO54              (<connected-to-hps_io_hps_io_gpio_inst_GPIO54>),              //                               .hps_io_gpio_inst_GPIO54
		.hps_io_hps_io_gpio_inst_GPIO61              (<connected-to-hps_io_hps_io_gpio_inst_GPIO61>),              //                               .hps_io_gpio_inst_GPIO61
		.i2s_clkctrl_apb_0_conduit_playback_lrclk    (<connected-to-i2s_clkctrl_apb_0_conduit_playback_lrclk>),    //      i2s_clkctrl_apb_0_conduit.playback_lrclk
		.i2s_clkctrl_apb_0_conduit_clk_sel_48_44     (<connected-to-i2s_clkctrl_apb_0_conduit_clk_sel_48_44>),     //                               .clk_sel_48_44
		.i2s_clkctrl_apb_0_conduit_master_slave_mode (<connected-to-i2s_clkctrl_apb_0_conduit_master_slave_mode>), //                               .master_slave_mode
		.i2s_clkctrl_apb_0_conduit_bclk              (<connected-to-i2s_clkctrl_apb_0_conduit_bclk>),              //                               .bclk
		.i2s_clkctrl_apb_0_conduit_capture_lrclk     (<connected-to-i2s_clkctrl_apb_0_conduit_capture_lrclk>),     //                               .capture_lrclk
		.i2s_clkctrl_apb_0_ext_bclk                  (<connected-to-i2s_clkctrl_apb_0_ext_bclk>),                  //          i2s_clkctrl_apb_0_ext.bclk
		.i2s_clkctrl_apb_0_ext_capture_lrclk         (<connected-to-i2s_clkctrl_apb_0_ext_capture_lrclk>),         //                               .capture_lrclk
		.i2s_clkctrl_apb_0_ext_playback_lrclk        (<connected-to-i2s_clkctrl_apb_0_ext_playback_lrclk>),        //                               .playback_lrclk
		.i2s_clkctrl_apb_0_mclk_clk                  (<connected-to-i2s_clkctrl_apb_0_mclk_clk>),                  //         i2s_clkctrl_apb_0_mclk.clk
		.i2s_output_apb_0_capture_dma_req            (<connected-to-i2s_output_apb_0_capture_dma_req>),            //   i2s_output_apb_0_capture_dma.req
		.i2s_output_apb_0_capture_dma_ack            (<connected-to-i2s_output_apb_0_capture_dma_ack>),            //                               .ack
		.i2s_output_apb_0_capture_dma_enable         (<connected-to-i2s_output_apb_0_capture_dma_enable>),         //                               .enable
		.i2s_output_apb_0_capture_fifo_data          (<connected-to-i2s_output_apb_0_capture_fifo_data>),          //  i2s_output_apb_0_capture_fifo.data
		.i2s_output_apb_0_capture_fifo_write         (<connected-to-i2s_output_apb_0_capture_fifo_write>),         //                               .write
		.i2s_output_apb_0_capture_fifo_full          (<connected-to-i2s_output_apb_0_capture_fifo_full>),          //                               .full
		.i2s_output_apb_0_capture_fifo_clk           (<connected-to-i2s_output_apb_0_capture_fifo_clk>),           //                               .clk
		.i2s_output_apb_0_capture_fifo_empty         (<connected-to-i2s_output_apb_0_capture_fifo_empty>),         //                               .empty
		.i2s_output_apb_0_playback_dma_req           (<connected-to-i2s_output_apb_0_playback_dma_req>),           //  i2s_output_apb_0_playback_dma.req
		.i2s_output_apb_0_playback_dma_ack           (<connected-to-i2s_output_apb_0_playback_dma_ack>),           //                               .ack
		.i2s_output_apb_0_playback_dma_enable        (<connected-to-i2s_output_apb_0_playback_dma_enable>),        //                               .enable
		.i2s_output_apb_0_playback_fifo_read         (<connected-to-i2s_output_apb_0_playback_fifo_read>),         // i2s_output_apb_0_playback_fifo.read
		.i2s_output_apb_0_playback_fifo_empty        (<connected-to-i2s_output_apb_0_playback_fifo_empty>),        //                               .empty
		.i2s_output_apb_0_playback_fifo_full         (<connected-to-i2s_output_apb_0_playback_fifo_full>),         //                               .full
		.i2s_output_apb_0_playback_fifo_clk          (<connected-to-i2s_output_apb_0_playback_fifo_clk>),          //                               .clk
		.i2s_output_apb_0_playback_fifo_data         (<connected-to-i2s_output_apb_0_playback_fifo_data>),         //                               .data
		.memory_mem_a                                (<connected-to-memory_mem_a>),                                //                         memory.mem_a
		.memory_mem_ba                               (<connected-to-memory_mem_ba>),                               //                               .mem_ba
		.memory_mem_ck                               (<connected-to-memory_mem_ck>),                               //                               .mem_ck
		.memory_mem_ck_n                             (<connected-to-memory_mem_ck_n>),                             //                               .mem_ck_n
		.memory_mem_cke                              (<connected-to-memory_mem_cke>),                              //                               .mem_cke
		.memory_mem_cs_n                             (<connected-to-memory_mem_cs_n>),                             //                               .mem_cs_n
		.memory_mem_ras_n                            (<connected-to-memory_mem_ras_n>),                            //                               .mem_ras_n
		.memory_mem_cas_n                            (<connected-to-memory_mem_cas_n>),                            //                               .mem_cas_n
		.memory_mem_we_n                             (<connected-to-memory_mem_we_n>),                             //                               .mem_we_n
		.memory_mem_reset_n                          (<connected-to-memory_mem_reset_n>),                          //                               .mem_reset_n
		.memory_mem_dq                               (<connected-to-memory_mem_dq>),                               //                               .mem_dq
		.memory_mem_dqs                              (<connected-to-memory_mem_dqs>),                              //                               .mem_dqs
		.memory_mem_dqs_n                            (<connected-to-memory_mem_dqs_n>),                            //                               .mem_dqs_n
		.memory_mem_odt                              (<connected-to-memory_mem_odt>),                              //                               .mem_odt
		.memory_mem_dm                               (<connected-to-memory_mem_dm>),                               //                               .mem_dm
		.memory_oct_rzqin                            (<connected-to-memory_oct_rzqin>),                            //                               .oct_rzqin
		.reset_reset_n                               (<connected-to-reset_reset_n>),                               //                          reset.reset_n
		.alt_vip_itc_0_clocked_video_vid_clk         (<connected-to-alt_vip_itc_0_clocked_video_vid_clk>),         //    alt_vip_itc_0_clocked_video.vid_clk
		.alt_vip_itc_0_clocked_video_vid_data        (<connected-to-alt_vip_itc_0_clocked_video_vid_data>),        //                               .vid_data
		.alt_vip_itc_0_clocked_video_underflow       (<connected-to-alt_vip_itc_0_clocked_video_underflow>),       //                               .underflow
		.alt_vip_itc_0_clocked_video_vid_datavalid   (<connected-to-alt_vip_itc_0_clocked_video_vid_datavalid>),   //                               .vid_datavalid
		.alt_vip_itc_0_clocked_video_vid_v_sync      (<connected-to-alt_vip_itc_0_clocked_video_vid_v_sync>),      //                               .vid_v_sync
		.alt_vip_itc_0_clocked_video_vid_h_sync      (<connected-to-alt_vip_itc_0_clocked_video_vid_h_sync>),      //                               .vid_h_sync
		.alt_vip_itc_0_clocked_video_vid_f           (<connected-to-alt_vip_itc_0_clocked_video_vid_f>),           //                               .vid_f
		.alt_vip_itc_0_clocked_video_vid_h           (<connected-to-alt_vip_itc_0_clocked_video_vid_h>),           //                               .vid_h
		.alt_vip_itc_0_clocked_video_vid_v           (<connected-to-alt_vip_itc_0_clocked_video_vid_v>)            //                               .vid_v
	);

